server:
  port: 8080

spring:
  application:
    name: dino.repo.api
  jpa:
    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/dinorepo
    username: user
    password: password
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
      skip:
        in-tests: true
  flyway:
    clean-disabled: false
    clean-on-validation-error: true
  springdoc:
    enable-native-support: true
  threads:
    virtual:
      enabled: true

